// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqydvtexsnyendavkqwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxeWR2dGV4c255ZW5kYXZrcXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzA5OTUsImV4cCI6MjA2OTg0Njk5NX0.hedP08qYZ9CxUYdXUyj5x3zpEu_UZpyXx-y2c_v0wkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});